name: iqlim
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.19.3 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  get: ^4.6.5
  get_storage: ^2.1.1
  tuple: ^2.0.0
  cached_network_image: ^3.1.0
  json_annotation:
  jiffy: ^4.1.0
  google_fonts: ^4.0.4
  fluttericon: ^2.0.0
  carousel_slider: ^4.2.1
  url_launcher: ^6.1.11
  flutter_easyloading: ^3.0.5
  graphql_flutter: ^5.1.2 #shopify
  freezed_annotation: ^2.2.0 #shopify
  json_serializable: ^6.6.1 #shopify
  shared_preferences: ^2.0.20 #shopify
  intl: ^0.17.0 #shopify

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^2.3.3 #shopify
  freezed: ^2.3.2 #shopify
  pedantic: ^1.11.1 #shopify
  flutter_lints: ^2.0.0 #shopify


flutter:

  uses-material-design: true

  assets:
    - assets/
